/**
 * Use Case data — single source of truth for the Use Case Finder.
 * Each entry mirrors INDEX.md with enriched fields for deal maker matching.
 */

/** The 10 fixed objections deal makers hear from prospects */
export const OBJECTIONS = [
  'Niche market, too specific for online marketing',
  'B2B sector, nobody searches for our services',
  'Our sector is too technical or complex for AI content',
  'Trust-sensitive sector where mistakes are not allowed',
  'We are too small for this kind of approach',
  'We tried it before and it didn\'t work',
  'It takes too long before you see results',
  'Our customers are not online',
  'We get everything from word of mouth',
  'We already do Google Ads, why also SEO',
] as const;

/** Dutch equivalents for bilingual chat matching */
export const OBJECTIONS_NL: Record<Objection, string> = {
  'Niche market, too specific for online marketing': 'niche markt te specifiek online marketing',
  'B2B sector, nobody searches for our services': 'b2b sector niemand zoekt onze diensten',
  'Our sector is too technical or complex for AI content': 'sector te technisch complex ai content',
  'Trust-sensitive sector where mistakes are not allowed': 'vertrouwensgevoelig fouten niet mogen medisch juridisch',
  'We are too small for this kind of approach': 'te klein voor dit soort aanpak',
  'We tried it before and it didn\'t work': 'eerder geprobeerd werkte niet',
  'It takes too long before you see results': 'duurt te lang voordat je iets ziet resultaten',
  'Our customers are not online': 'klanten zitten niet online',
  'We get everything from word of mouth': 'mond-tot-mondreclame mond tot mond',
  'We already do Google Ads, why also SEO': 'google ads waarom ook seo advertenties',
};

export type Objection = typeof OBJECTIONS[number];
export type BusinessType = 'B2B' | 'B2C' | 'Mix';
export type MarketPosition = 'Niche' | 'Mainstream';

export interface UseCase {
  id: string;
  company: string;
  industry: string;
  painPattern: string;
  headline: string;
  outcome: string;
  result: string;
  summary: string;
  businessType: BusinessType;
  marketPosition: MarketPosition;
  trustSensitive: boolean;
  objections: Objection[];
  countries: string[];
  keywords: string[];
  pdfFile: string;
}

export const useCases: UseCase[] = [
  // ── No time / capacity for SEO ──────────────────────────────────────────────
  {
    id: 'kinwell',
    company: 'Kinwell',
    industry: 'Health & Wellness',
    painPattern: 'No time / capacity for SEO',
    headline: 'No capacity for SEO',
    outcome: 'Freed capacity',
    result: 'Went from zero SEO activity to consistent content output and ranking improvements without hiring additional staff.',
    summary: 'Kinwell had no bandwidth to work on SEO alongside their core business. WP SEO AI automated their content and optimization workflow, letting them compete online without adding headcount.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: true,
    objections: [
      'We are too small for this kind of approach',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'busy', 'resource', 'team too small', 'bandwidth', 'no one available', 'health', 'wellness'],
    pdfFile: 'No capacity for SEO - Kinwell - Success case.pdf',
  },
  {
    id: 'roelands',
    company: 'Roelands Boomkwekerijen',
    industry: 'Agriculture / Nursery',
    painPattern: 'No time / capacity for SEO',
    headline: 'No time & capacity for SEO',
    outcome: 'Freed capacity',
    result: 'Built a full SEO presence for their nursery business while the team stayed focused on growing and selling plants.',
    summary: 'A traditional nursery business with no marketing team. WP SEO AI handled SEO end-to-end so the owners could focus on their core work while gaining online visibility in a niche B2B segment.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'B2B sector, nobody searches for our services',
      'Our customers are not online',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'agriculture', 'nursery', 'plants', 'grower', 'horticulture'],
    pdfFile: 'No time & capacity - Roelands Boomkwekerijen - Success case.pdf',
  },
  {
    id: 'mydearbeer',
    company: 'My Dear Beer',
    industry: 'F&B / Retail',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Grew organic webshop traffic significantly while the small team kept running day-to-day retail operations.',
    summary: 'Small specialty beer retailer with an online shop and no time for SEO. WP SEO AI automated product page optimization and content creation, driving organic traffic growth to the webshop.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We are too small for this kind of approach',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'food', 'beverage', 'retail', 'drinks', 'beer', 'ecommerce', 'webshop'],
    pdfFile: 'Too little time for SEO  - My Dear Beer - Success case.pdf',
  },
  {
    id: 'verdonk',
    company: 'Autobedrijven Verdonk',
    industry: 'Automotive',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Achieved consistent local search visibility across multiple dealership locations without dedicating internal staff to marketing.',
    summary: 'Multi-location car dealer with no marketing team. WP SEO AI optimized their local presence and content for each location, driving leads while the team focused on selling cars.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'We get everything from word of mouth',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'automotive', 'car', 'cars', 'dealer', 'garage', 'vehicles'],
    pdfFile: 'Too little time for SEO - Autobedrijven Verdonk - Success case.pdf',
  },
  {
    id: 'searchx',
    company: 'SearchX',
    industry: 'Agency',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Scaled SEO delivery for their clients without proportionally growing the team, improving margins per client.',
    summary: 'Marketing agency struggling to scale SEO delivery. WP SEO AI became their white-label execution layer, letting them serve more clients with the same team size.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'Our sector is too technical or complex for AI content',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'agency', 'marketing agency', 'seo agency', 'white label'],
    pdfFile: 'Too little time for SEO - SearchX - Success case.pdf',
  },
  {
    id: 'berendijk',
    company: 'Timmerbedrijf Berendijk',
    industry: 'Construction',
    painPattern: 'No time / capacity for SEO',
    headline: 'Too little time for SEO',
    outcome: 'Freed capacity',
    result: 'Went from invisible online to ranking for key local construction searches, generating inbound leads for the first time.',
    summary: 'Small construction firm that relied entirely on word of mouth. Had zero online presence and no time to build one. WP SEO AI automated their local SEO and content, opening a new lead channel.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'Our customers are not online',
      'We get everything from word of mouth',
    ],
    countries: ['Netherlands'],
    keywords: ['no time', 'capacity', 'construction', 'building', 'contractor', 'timber'],
    pdfFile: 'Too little time for SEO - Timmerbedrijf Berendijk - Success case.pdf',
  },

  // ── Underperforming agency / high SEO cost ─────────────────────────────────
  {
    id: 'eleven',
    company: 'ELEVEN',
    industry: 'Creative / Media',
    painPattern: 'Underperforming agency / high SEO cost',
    headline: 'Underperforming agency, no in-house team, AI search advantage',
    outcome: 'Replaced agency, AI search advantage',
    result: 'Replaced their underperforming agency, cut costs, and gained early visibility in AI search results like ChatGPT.',
    summary: 'ELEVEN had no in-house marketing team and an agency that wasn\'t delivering. WP SEO AI replaced the agency entirely, providing better results at lower cost while positioning them for AI search.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['agency', 'underperforming', 'bad agency', 'no results', 'expensive', 'no marketing team', 'ai search', 'in-house'],
    pdfFile: 'Underperforming Agency - AI Search - No Inhouse Marketing Team -ELEVEN - .pdf',
  },
  {
    id: 'vleesandco',
    company: 'Vlees & Co',
    industry: 'F&B / Wholesale',
    painPattern: 'Underperforming agency / high SEO cost',
    headline: 'Underperforming agency',
    outcome: 'Replaced agency',
    result: 'Transitioned away from an expensive agency to an AI-driven approach with better content quality and consistency.',
    summary: 'B2B food wholesaler whose SEO agency was delivering poor results. WP SEO AI replaced the agency, producing more relevant content faster and at a fraction of the cost.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'B2B sector, nobody searches for our services',
    ],
    countries: ['Netherlands'],
    keywords: ['agency', 'underperforming', 'bad agency', 'food', 'meat', 'wholesale'],
    pdfFile: 'Underperforming agency - Vlees & Co  - Success case .pdf',
  },
  {
    id: 'broekman',
    company: 'Broekman',
    industry: 'Retail',
    painPattern: 'Underperforming agency / high SEO cost',
    headline: 'High SEO cost with limited impact',
    outcome: 'Reduced cost, better results',
    result: 'Cut SEO spend significantly while achieving more traffic and conversions than the previous expensive agency setup.',
    summary: 'Retail company paying high agency fees with minimal ROI. WP SEO AI delivered better results at a fraction of the cost, proving that AI-powered SEO beats traditional agency models for their use case.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'We already do Google Ads, why also SEO',
    ],
    countries: ['Netherlands'],
    keywords: ['expensive', 'cost', 'high cost', 'roi', 'agency', 'retail', 'limited impact', 'wasting money'],
    pdfFile: 'High SEO cost with limited impact - Broekman - Success case - Retail .pdf',
  },

  // ── AI / LLM search opportunity ────────────────────────────────────────────
  {
    id: 'kruijdenberg',
    company: 'Kruijdenberg',
    industry: 'Industrial / Manufacturing',
    painPattern: 'AI / LLM search opportunity',
    headline: 'AI curiosity & LLM search advantage',
    outcome: 'LLM search visibility',
    result: 'Became one of the first in their industry to appear in ChatGPT and AI search results, capturing early-mover advantage.',
    summary: 'Industrial company curious about AI search but unsure how to act. WP SEO AI structured their content for LLM visibility, resulting in early presence in AI-generated answers for their niche.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'Our sector is too technical or complex for AI content',
    ],
    countries: ['Netherlands'],
    keywords: ['ai', 'llm', 'chatgpt', 'ai search', 'ai overviews', 'future', 'innovation', 'curious', 'industrial', 'manufacturing'],
    pdfFile: 'Ai curiosity & LLM search advantage - Kruijdenberg - Success case.pdf',
  },
  {
    id: 'wijzijntop',
    company: 'Wijzijntop',
    industry: 'Services',
    painPattern: 'AI / LLM search opportunity',
    headline: 'AI curiosity but no strategy',
    outcome: 'AI strategy implemented',
    result: 'Went from AI-curious to having a structured AI search strategy with measurable visibility in LLM results.',
    summary: 'Knew AI search was important but had no idea where to start. WP SEO AI provided the strategy and execution to make their content AI-discoverable across ChatGPT and other LLMs.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['ai', 'llm', 'chatgpt', 'strategy', 'no plan', 'ai search', 'direction'],
    pdfFile: 'AI curiosity but no strategy - Wijzijntop- Success case.pdf',
  },
  {
    id: 'catermonkey',
    company: 'Catermonkey',
    industry: 'Catering / Events',
    painPattern: 'AI / LLM search opportunity',
    headline: 'Insane lead flow from ChatGPT & other LLMs',
    outcome: 'Lead flow from LLMs',
    result: 'Generated a significant new lead stream directly from ChatGPT and other LLM platforms, a channel competitors hadn\'t tapped.',
    summary: 'Catering platform that discovered massive lead potential from AI search. WP SEO AI optimized their content for LLM discoverability, resulting in a new acquisition channel their competitors don\'t have.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['ai', 'llm', 'chatgpt', 'leads', 'lead generation', 'catering', 'food', 'events'],
    pdfFile: 'Insane lead flow from Chat-gpt & other LLM_s - Catermonkey - Success case.pdf',
  },

  // ── Relied on single channel ───────────────────────────────────────────────
  {
    id: 'vandenakker',
    company: 'Autobedrijf Van den Akker',
    industry: 'Automotive',
    painPattern: 'Relied on single channel',
    headline: 'Relied on word of mouth',
    outcome: 'Diversified acquisition',
    result: 'Built a consistent online lead channel alongside word-of-mouth, reducing dependency on referrals alone.',
    summary: 'Car dealer that depended entirely on word of mouth. WP SEO AI built their organic search presence from scratch, creating a second acquisition channel that generates leads independently.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We get everything from word of mouth',
      'Our customers are not online',
    ],
    countries: ['Netherlands'],
    keywords: ['word of mouth', 'referral', 'one channel', 'single channel', 'automotive', 'car', 'dealer'],
    pdfFile: 'Relied on word of mouth - Autobedrijf Van den Akker - Success case.pdf',
  },
  {
    id: 'schulte-wom',
    company: 'Schulte Energie & Techniek',
    industry: 'Energy / Installation',
    painPattern: 'Relied on single channel',
    headline: 'Relied on word of mouth',
    outcome: 'Diversified acquisition',
    result: 'Opened an organic search channel that now generates leads alongside their existing referral network.',
    summary: 'Energy and installation company that relied solely on word of mouth. WP SEO AI created an online presence that attracts new customers who aren\'t in their existing referral network.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We get everything from word of mouth',
      'Niche market, too specific for online marketing',
      'Our customers are not online',
    ],
    countries: ['Netherlands'],
    keywords: ['word of mouth', 'referral', 'energy', 'sustainability', 'green', 'solar', 'techniek', 'installation', 'hvac', 'heating', 'renewable'],
    pdfFile: 'Relied on word of mouth - Schulte Energie & Techniek - Success case.pdf',
  },
  {
    id: 'ckactive',
    company: 'CK Active',
    industry: 'Sports / Fitness',
    painPattern: 'Relied on single channel',
    headline: 'Relied heavily on SEA / Google Ads',
    outcome: 'Reduced SEA dependency',
    result: 'Reduced Google Ads spend while maintaining lead volume by building an organic search foundation.',
    summary: 'Fitness business spending heavily on Google Ads with no organic presence. WP SEO AI built their SEO base so they could reduce ad spend without losing leads.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We already do Google Ads, why also SEO',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['google ads', 'sea', 'paid', 'ads', 'advertising', 'ppc', 'adwords', 'ad spend', 'sports', 'fitness'],
    pdfFile: 'Relied heaviliy on SEA - CK Active - Success case.pdf',
  },

  // ── Lack of control / visibility ───────────────────────────────────────────
  {
    id: 'sillegallery',
    company: 'Sille Gallery',
    industry: 'Retail / Art',
    painPattern: 'Lack of control / visibility',
    headline: 'Lack of control over SEO',
    outcome: 'Gained SEO control',
    result: 'Gained full visibility into their SEO performance and took control of their search strategy for the first time.',
    summary: 'Art gallery retailer that had no insight into what was happening with their SEO. WP SEO AI gave them a clear dashboard and hands-on control over their search visibility strategy.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'We tried it before and it didn\'t work',
    ],
    countries: ['Netherlands'],
    keywords: ['control', 'visibility', 'art', 'gallery', 'retail', 'no insight', 'dashboard', 'reporting'],
    pdfFile: 'Lack of Control Over SEO - Sille Gallery - Success case.pdf',
  },
  {
    id: 'cooffice',
    company: 'Co-Office',
    industry: 'Real Estate / Flex Office',
    painPattern: 'Lack of control / visibility',
    headline: 'Traffic drop during site transition',
    outcome: 'Recovered from traffic drop',
    result: 'Fully recovered organic traffic after a website migration that had caused a severe rankings drop.',
    summary: 'Flex office provider that lost significant traffic during a website migration. WP SEO AI identified the technical issues, rebuilt their content strategy, and recovered their rankings.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
    ],
    countries: ['Netherlands'],
    keywords: ['traffic drop', 'migration', 'site transition', 'new website', 'relaunch', 'real estate', 'office', 'coworking', 'flex'],
    pdfFile: 'Traffic drop during site transition - Co-Office - Success case.pdf',
  },

  // ── Going international / scaling ──────────────────────────────────────────
  {
    id: 'geldzo',
    company: 'GeldZo',
    industry: 'Finance / Fintech',
    painPattern: 'Going international / scaling',
    headline: 'No time for manual work and going international',
    outcome: 'International SEO',
    result: 'Launched SEO in multiple new markets simultaneously without expanding the marketing team.',
    summary: 'Fintech company expanding internationally but couldn\'t scale manual SEO across languages. WP SEO AI automated multilingual content and optimization, enabling market entry in multiple countries at once.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: true,
    objections: [
      'It takes too long before you see results',
      'We are too small for this kind of approach',
    ],
    countries: ['Netherlands', 'International'],
    keywords: ['international', 'global', 'expand', 'multilingual', 'multiple countries', 'finance', 'fintech', 'scaling'],
    pdfFile: 'No time for manual work and going international - GeldZo - Success Case .pdf',
  },
  {
    id: 'pbn',
    company: 'PBN',
    industry: 'Professional Services',
    painPattern: 'Going international / scaling',
    headline: 'No time for manual work and going international',
    outcome: 'International SEO',
    result: 'Successfully scaled their SEO presence to new international markets while keeping the same lean team.',
    summary: 'Professional services firm going international with limited marketing resources. WP SEO AI handled multilingual SEO execution so they could enter new markets without hiring local content teams.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We are too small for this kind of approach',
      'B2B sector, nobody searches for our services',
    ],
    countries: ['Netherlands', 'International'],
    keywords: ['international', 'global', 'expand', 'multilingual', 'multiple countries', 'scaling', 'professional services'],
    pdfFile: 'No time for manual work and going international - PBN - Success Case .pdf',
  },

  // ── Efficiency gap ─────────────────────────────────────────────────────────
  {
    id: 'officebox',
    company: 'Officebox',
    industry: 'Office Supplies',
    painPattern: 'Efficiency gap',
    headline: 'Efficiency gap',
    outcome: 'Efficiency gains',
    result: 'Automated SEO for thousands of product pages, eliminating hours of manual optimization work per week.',
    summary: 'B2B office supplies company with a large product catalog and no efficient way to optimize it. WP SEO AI automated bulk optimization across thousands of pages, saving significant manual effort.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
      'We already do Google Ads, why also SEO',
    ],
    countries: ['Netherlands'],
    keywords: ['efficiency', 'manual work', 'slow', 'time-consuming', 'office', 'supplies', 'b2b', 'product pages', 'catalog'],
    pdfFile: 'Efficiency gap - Officebox -.pdf',
  },
  {
    id: 'implicit',
    company: 'IMPLI-CIT',
    industry: 'IT / Software',
    painPattern: 'Efficiency gap',
    headline: 'Efficiency gap and new customers',
    outcome: 'Efficiency + new customers',
    result: 'Streamlined their content workflow and started attracting new customer segments through organic search.',
    summary: 'IT company that was spending too much time on manual SEO tasks with limited results. WP SEO AI made their process efficient and opened up new customer acquisition channels they hadn\'t reached before.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'Our sector is too technical or complex for AI content',
    ],
    countries: ['Netherlands'],
    keywords: ['efficiency', 'new customers', 'growth', 'manual', 'leads', 'it', 'software', 'tech'],
    pdfFile: 'Efficiency gap and new customers - IMPLI-CIT - Success case.pdf',
  },

  // ── Limited marketing capacity ─────────────────────────────────────────────
  {
    id: 'dercsalotech',
    company: 'DERC Salotech',
    industry: 'Industrial / Tech',
    painPattern: 'Limited marketing capacity',
    headline: 'From limited marketing capacity to AI-ready SEO',
    outcome: 'AI-ready SEO',
    result: 'Built a complete AI-ready SEO strategy from scratch despite having no dedicated marketing resources.',
    summary: 'Industrial tech company with no marketing team and zero SEO foundation. WP SEO AI built their entire search strategy from the ground up, including AI search readiness, with minimal input needed from the client.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'B2B sector, nobody searches for our services',
      'Our sector is too technical or complex for AI content',
      'We are too small for this kind of approach',
    ],
    countries: ['Netherlands'],
    keywords: ['limited marketing', 'small team', 'no marketer', 'industrial', 'manufacturing', 'tech', 'b2b', 'ai-ready'],
    pdfFile: 'From limited marketing capacity to AI-ready SEO - DERC Salotech - Success Case - .pdf',
  },
  {
    id: 'schulte-scale',
    company: 'Schulte Energie & Techniek',
    industry: 'Energy / Installation',
    painPattern: 'Limited marketing capacity',
    headline: 'Limited capacity to scale for AI',
    outcome: 'Scaled for AI',
    result: 'Scaled their marketing output for AI search readiness without growing the team.',
    summary: 'Energy installation company that knew AI search was coming but lacked the marketing capacity to prepare. WP SEO AI automated their content scaling so they\'re positioned for the AI search shift.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'Our customers are not online',
      'We get everything from word of mouth',
      'We are too small for this kind of approach',
    ],
    countries: ['Netherlands'],
    keywords: ['limited marketing', 'scale', 'ai', 'energy', 'sustainability', 'green', 'solar', 'techniek', 'installation', 'hvac', 'heating', 'renewable'],
    pdfFile: 'Schulte Energie & Techniek - Limited Capacity to Scale for AI .pdf',
  },

  // ── Other ──────────────────────────────────────────────────────────────────
  {
    id: 'kwiz',
    company: 'KWIZ',
    industry: 'Entertainment / Leisure',
    painPattern: 'Other',
    headline: 'New website & didn\'t like SEO copywriter',
    outcome: 'Replaced copywriter',
    result: 'Replaced an expensive SEO copywriter with AI-generated content that better matched their brand voice and converted better.',
    summary: 'KWIZ launched a new website but the SEO copywriter produced generic, low-quality content. WP SEO AI delivered brand-aligned content at scale, better quality and significantly lower cost.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
    ],
    countries: ['Netherlands'],
    keywords: ['copywriter', 'content', 'new website', 'writing', 'copy', 'quality', 'entertainment', 'leisure'],
    pdfFile: 'New website & didnt like SEO copy writer - KWIZ Success Case - NL -  .pdf',
  },
  {
    id: 'ctalents',
    company: 'CTalents',
    industry: 'Recruitment / HR',
    painPattern: 'Other',
    headline: 'Struggled to keep up with developments in search behaviour',
    outcome: 'Kept up with search evolution',
    result: 'Stayed ahead of changing search behaviour patterns, maintaining visibility as candidates shifted how they search.',
    summary: 'Recruitment firm struggling to keep up as candidate search behaviour evolved rapidly. WP SEO AI kept their content strategy current with the latest search trends, including AI-driven search.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
      'B2B sector, nobody searches for our services',
    ],
    countries: ['Netherlands'],
    keywords: ['search behaviour', 'changing landscape', 'keep up', 'recruitment', 'staffing', 'hr', 'talent'],
    pdfFile: 'Struggled to keep up with developments in search behaviour - CTalents - Success Case.pdf',
  },

  // ── New cases (April 2026) ─────────────────────────────────────────────────
  {
    id: 'ebikesde',
    company: 'ebikes.de',
    industry: 'E-commerce / Consumer Media',
    painPattern: 'No time / capacity for SEO',
    headline: 'Efficiency gap — strong domain but no time for content at scale',
    outcome: '+24,220% AI content traffic growth',
    result: '240 AI-optimized articles published in 9 months. +12,031 AI-attributed clicks, 1.25M impressions, traffic worth valued at €8,769. Content cited in ChatGPT and Google AI Overviews.',
    summary: 'German e-bike specialist portal with strong domain authority but a tiny team juggling research, content, and optimization. WP SEO AI scaled content production across key keyword clusters, driving massive organic and AI search growth.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'It takes too long before you see results',
      'We are too small for this kind of approach',
    ],
    countries: ['Germany'],
    keywords: ['e-bikes', 'ecommerce', 'ebike', 'german', 'germany', 'content at scale', 'ai overviews', 'chatgpt', 'consumer'],
    pdfFile: 'Efficiency Gap - e-bikes.de - Success case (ENGLISH).pdf',
  },
  {
    id: 'medici',
    company: 'Medici Vermittlung',
    industry: 'Healthcare / Medical Staffing',
    painPattern: 'Relied on single channel',
    headline: 'SEA budget fixed with SEO content — from paid dependency to organic growth',
    outcome: '+253% organic clicks, €10K traffic value',
    result: 'Organic clicks grew from 826 to 2,912 (+253%). Impressions up +551%. 82% of traffic from AI content. Visible in Google AI Overviews for key medical queries. Traffic worth €10,325.',
    summary: 'German medical recruitment agency with almost zero organic presence and unsustainable paid search costs. WP SEO AI published 196 articles in 5 months, fully automated, shifting acquisition from SEA to organic and AI search.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: true,
    objections: [
      'Trust-sensitive sector where mistakes are not allowed',
      'B2B sector, nobody searches for our services',
      'We already do Google Ads, why also SEO',
      'We are too small for this kind of approach',
    ],
    countries: ['Germany'],
    keywords: ['medical', 'healthcare', 'doctors', 'recruitment', 'staffing', 'sea', 'google ads', 'paid search', 'german', 'germany'],
    pdfFile: 'SEA budget fixed with SEO Content - Medici ENG - Success case (ENGLISH) .pdf',
  },
  {
    id: 'adelt-ideen',
    company: 'IP Adelt',
    industry: 'B2B / Visual Displays',
    painPattern: 'Lack of control / visibility',
    headline: 'No organic inbound acquisition — zero visibility to +470% growth',
    outcome: '+470% organic growth in 6 months',
    result: '+470% organic growth in 6 months (195 to 1,111 monthly clicks). 46.2% of clicks from AI content. Traffic worth €6,616. Featured in Google AI Overviews.',
    summary: 'German B2B company for product presentation systems with zero organic acquisition. Most product pages weren\'t live and the broad portfolio made focus difficult. WP SEO AI built their organic channel from scratch.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'Niche market, too specific for online marketing',
      'Our customers are not online',
    ],
    countries: ['Germany'],
    keywords: ['visual displays', 'product presentation', 'b2b', 'german', 'germany', 'no organic', 'zero visibility', 'inbound'],
    pdfFile: 'No organic inbound acquisition - adelt-ideen.de - GERMAN  (1).pdf',
  },
  {
    id: 'quest-search',
    company: 'Quest Search and Selection',
    industry: 'Recruitment / HR',
    painPattern: 'Limited marketing capacity',
    headline: 'From marginal organic traffic to 775% growth and AI Overview dominance',
    outcome: '+775% organic traffic, €13.8K traffic value',
    result: '775% organic traffic growth. WP SEO AI share of clicks grew from 5% to 42%. +71K impressions/month. €13,828 traffic value. Now dominates Google AI Overviews with multiple articles per result.',
    summary: 'Recruitment agency that knew SEO was key but lacked a content strategy. WP SEO AI built and executed their entire organic content engine, growing them from marginal traffic to dominating AI Overviews in their niche.',
    businessType: 'B2B',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'B2B sector, nobody searches for our services',
      'It takes too long before you see results',
    ],
    countries: ['United Kingdom'],
    keywords: ['recruitment', 'hr', 'staffing', 'search and selection', 'ai overviews', 'content strategy'],
    pdfFile: 'Quest search - Success case.pdf',
  },
  {
    id: 'greenstay',
    company: 'Greenstay',
    industry: 'Real Estate / Short-Stay Rentals',
    painPattern: 'Lack of control / visibility',
    headline: 'From zero SEO to 5x traffic and 100+ leads/month',
    outcome: '5x traffic, 100+ leads, 13% conversion rate',
    result: 'Organic traffic increased fivefold in 6 months. 100+ leads in August. 13% conversion rate vs 4% industry benchmark. Leads up +300%, cost of acquisition down -62%. Traffic worth €4,178.',
    summary: 'Amsterdam short-stay housing provider with zero SEO efforts. WP SEO AI built their entire organic presence from scratch, achieving a conversion rate 3x the industry benchmark and dramatically lowering acquisition costs.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'It takes too long before you see results',
    ],
    countries: ['Netherlands'],
    keywords: ['short stay', 'housing', 'amsterdam', 'rental', 'real estate', 'leads', 'conversion', 'accommodation'],
    pdfFile: 'Greenstay - Success Case.pdf',
  },
  {
    id: 'salon-klipsi',
    company: 'Salon Klipsi',
    industry: 'Beauty / Personal Care',
    painPattern: 'No time / capacity for SEO',
    headline: 'Hair salon ranking #1 on Google with AI-powered SEO',
    outcome: '+57% organic traffic, #1 rankings',
    result: '+57% organic traffic in 8 months. +295% jump in top 3 rankings. Ranking #1 for high-intent terms. 41% of clicks from AI content. Scaled from 10 to 20+ articles/month.',
    summary: 'Finnish hair salon where clients were clearly searching on Google but the salon lacked time and SEO expertise. WP SEO AI automated their content at scale, pushing them to #1 positions for high-intent local searches.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We are too small for this kind of approach',
      'Our customers are not online',
    ],
    countries: ['Finland'],
    keywords: ['salon', 'hair', 'beauty', 'finland', 'finnish', 'local seo', 'bookings', 'personal care'],
    pdfFile: 'Salon Klipsi - Success Case.pdf',
  },
  {
    id: 'moneybee',
    company: 'Moneybee',
    industry: 'B2B Financial Services / Accounting',
    painPattern: 'Limited marketing capacity',
    headline: '6-person accounting firm outranking national giants',
    outcome: '+372% organic traffic, €7.90 ROI per €1',
    result: '+372% organic traffic in 8 months. Outranking firms 20x their size. 90% of organic clicks from AI content. Every €1 spent earned €7.90 in CPC-equivalent traffic value. Leads grew fast enough to hire an additional colleague.',
    summary: 'Tiny Finnish accounting firm (6 people) competing against national players with no marketing staff. WP SEO AI turned them into an organic search powerhouse, outranking companies 20x their size and generating enough leads to grow the team.',
    businessType: 'B2B',
    marketPosition: 'Niche',
    trustSensitive: true,
    objections: [
      'We are too small for this kind of approach',
      'B2B sector, nobody searches for our services',
      'Trust-sensitive sector where mistakes are not allowed',
    ],
    countries: ['Finland'],
    keywords: ['accounting', 'finance', 'bookkeeping', 'finland', 'finnish', 'small business', 'b2b', 'roi'],
    pdfFile: 'Moneybee - Success Case.pdf',
  },
  {
    id: 'pest1',
    company: 'Pest1',
    industry: 'Home Services / Pest Control',
    painPattern: 'No time / capacity for SEO',
    headline: 'Pest control company quadruples organic traffic with AI content',
    outcome: '+339% organic growth, #1 in Google',
    result: '+339% organic traffic growth in less than a year. 95% of clicks from AI-optimized content. Ranking #1 in Google and featured in AI Overviews. Traffic worth €3,129. Seasonal content published proactively.',
    summary: 'Finnish pest control business with low online visibility despite search being critical for customer acquisition. WP SEO AI automated content production including proactive seasonal content, quadrupling their organic traffic.',
    businessType: 'B2C',
    marketPosition: 'Niche',
    trustSensitive: false,
    objections: [
      'Niche market, too specific for online marketing',
      'It takes too long before you see results',
      'Our customers are not online',
    ],
    countries: ['Finland'],
    keywords: ['pest control', 'home services', 'finland', 'finnish', 'seasonal', 'local', 'exterminator'],
    pdfFile: 'Pest1 Success Case.pdf',
  },
  {
    id: 'aimo-park',
    company: 'Aimo Park',
    industry: 'Mobility / Parking',
    painPattern: 'Lack of control / visibility',
    headline: '40-year brand invisible in non-branded search — now #1 with AI citations',
    outcome: '+203% non-branded clicks, ChatGPT citations',
    result: '+203% extra clicks in non-branded search. 1,500 extra clicks/month. #1 positions with featured snippets. Articles cited as source in ChatGPT responses for parking-related questions.',
    summary: 'Scandinavian parking operator with 40 years of history but completely invisible to anyone not already searching by brand name. WP SEO AI captured high-intent long-tail keywords, earning #1 positions and ChatGPT citations.',
    businessType: 'B2C',
    marketPosition: 'Mainstream',
    trustSensitive: false,
    objections: [
      'We tried it before and it didn\'t work',
      'It takes too long before you see results',
    ],
    countries: ['Sweden', 'Scandinavia'],
    keywords: ['parking', 'mobility', 'stockholm', 'scandinavia', 'sweden', 'brand', 'non-branded', 'chatgpt', 'featured snippets'],
    pdfFile: 'Aimo Park - Success Case.pdf',
  },
];

/** All unique pain patterns */
export const painPatterns = [...new Set(useCases.map((c) => c.painPattern))];

/** All unique industries */
export const industries = [...new Set(useCases.map((c) => c.industry))];

/** Objection counts — how many cases address each objection */
export const objectionCounts = OBJECTIONS.map((obj) => ({
  objection: obj,
  count: useCases.filter((c) => c.objections.includes(obj)).length,
}));
